// Code generated by idlgen. DO NOT EDIT.

package v1

import (
	"context"
	"encoding/json"

	rpcwirev1 "github.com/floegence/flowersec/flowersec-go/gen/flowersec/rpc/v1"
	"github.com/floegence/flowersec/flowersec-go/rpc"
)

// Hello notification.
const DemoTypeID_Hello uint32 = 2

// Ping request/response.
const DemoTypeID_Ping uint32 = 1

// Demo service used by examples and integration tests.
type DemoClient struct {
	c *rpc.Client
}

func NewDemoClient(c *rpc.Client) *DemoClient { return &DemoClient{c: c} }

type DemoHandler interface {
	// Ping request/response.
	Ping(ctx context.Context, req *PingRequest) (*PingResponse, error)
}

func RegisterDemo(r *rpc.Router, h DemoHandler) {
	r.Register(DemoTypeID_Ping, func(ctx context.Context, payload json.RawMessage) (json.RawMessage, *rpcwirev1.RpcError) {
		var req PingRequest
		if len(payload) != 0 {
			if err := json.Unmarshal(payload, &req); err != nil {
				return nil, rpc.ToWireError(&rpc.Error{Code: 400, Message: "invalid payload"})
			}
		}
		resp, err := h.Ping(ctx, &req)
		if err != nil {
			return nil, rpc.ToWireError(err)
		}
		var zero PingResponse
		if resp == nil {
			resp = &zero
		}
		b, err := json.Marshal(resp)
		if err != nil {
			return nil, rpc.ToWireError(err)
		}
		return b, nil
	})

}

// Hello notification.
func (x *DemoClient) OnHello(h func(*HelloNotify)) (unsubscribe func()) {
	return x.c.OnNotify(DemoTypeID_Hello, func(payload json.RawMessage) {
		var msg HelloNotify
		if err := json.Unmarshal(payload, &msg); err != nil {
			return
		}
		h(&msg)
	})
}

// Hello notification.
func NotifyDemoHello(n interface {
	Notify(uint32, json.RawMessage) error
}, msg *HelloNotify) error {
	if msg == nil {
		msg = &HelloNotify{}
	}
	b, err := json.Marshal(msg)
	if err != nil {
		return err
	}
	return n.Notify(DemoTypeID_Hello, b)
}

// Ping request/response.
func (x *DemoClient) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	if req == nil {
		req = &PingRequest{}
	}
	b, err := json.Marshal(req)
	if err != nil {
		return nil, err
	}
	payload, rpcErr, err := x.c.Call(ctx, DemoTypeID_Ping, b)
	if err != nil {
		return nil, err
	}
	if rpcErr != nil {
		return nil, rpc.NewCallError(DemoTypeID_Ping, rpcErr)
	}
	var resp PingResponse
	if len(payload) != 0 {
		if err := json.Unmarshal(payload, &resp); err != nil {
			return nil, err
		}
	}
	return &resp, nil
}
