package interopharness

import (
	"bytes"
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"errors"
	"io"
	"net"
	"net/http"
	"net/url"

	"github.com/floegence/flowersec/flowersec-go/v6/internal/assemblyv4"
	"github.com/floegence/flowersec/flowersec-go/v6/internal/protocolv4"
)

// HTTPSBootstrap uses independent root pins and bounded complete authority
// replies. Requests use the nonce generated by the original bootstrap owner.
// No implicit redirect, cache, retry or peer-provided clock is accepted.
type HTTPSBootstrap struct {
	record NamespaceRecord
	client *http.Client
	state  []byte
}

func NewHTTPSBootstrap(record NamespaceRecord, trustPEM string, scopes ...assemblyv4.NativeDialScope) (*HTTPSBootstrap, error) {
	if len(scopes) > 1 {
		return nil, errors.New("one original bootstrap network scope is required")
	}
	var scope assemblyv4.NativeDialScope
	if len(scopes) == 1 {
		scope = scopes[0]
	}
	roots := x509.NewCertPool()
	if !roots.AppendCertsFromPEM([]byte(trustPEM)) {
		return nil, errors.New("bootstrap TLS roots are missing")
	}
	for _, address := range []string{record.BootstrapURL, record.StateURL} {
		parsed, err := url.Parse(address)
		if err != nil || parsed.Scheme != "https" || parsed.Host == "" || parsed.User != nil || parsed.Fragment != "" {
			return nil, errors.New("invalid independent bootstrap URL")
		}
	}
	// A cold query must relinquish its finite authority socket before the
	// independent prepared runtime is retained for later connection admission.
	transport := &http.Transport{DialContext: scopedControlDial(scope), TLSClientConfig: &tls.Config{MinVersion: tls.VersionTLS13, MaxVersion: tls.VersionTLS13, RootCAs: roots}, MaxConnsPerHost: 1, DisableKeepAlives: true, DisableCompression: true}
	return &HTTPSBootstrap{record: record, client: &http.Client{Transport: transport, CheckRedirect: func(*http.Request, []*http.Request) error { return errors.New("bootstrap redirects are forbidden") }}}, nil
}
func (p *HTTPSBootstrap) Query(ctx context.Context, request protocolv4.NamespaceBootstrapRequest, output []byte) (int, error) {
	if request.Tenant != p.record.Tenant || request.Authority != p.record.Authority {
		return 0, errors.New("independent bootstrap namespace mismatch")
	}
	wire, err := json.Marshal(BootstrapRequest{Tenant: request.Tenant, Authority: request.Authority, Nonce: request.Nonce[:]})
	if err != nil {
		return 0, err
	}
	query, err := http.NewRequestWithContext(ctx, http.MethodPost, p.record.BootstrapURL, bytes.NewReader(wire))
	if err != nil {
		return 0, err
	}
	query.Header.Set("Content-Type", "application/json")
	response, err := p.client.Do(query)
	if err != nil {
		return 0, err
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return 0, errors.New("bootstrap authority refused query")
	}
	data, err := io.ReadAll(io.LimitReader(response.Body, 65537))
	if err != nil || len(data) > 65536 {
		return 0, errors.New("bootstrap response exceeds bound")
	}
	var result BootstrapResponse
	if err = json.Unmarshal(data, &result); err != nil {
		return 0, err
	}
	if len(result.Response) == 0 || len(result.Response) > len(output) || len(result.State) == 0 || len(result.State) > 4096 {
		return 0, errors.New("bootstrap canonical reply exceeds bound")
	}
	p.state = append(p.state[:0], result.State...)
	return copy(output, result.Response), nil
}
func (p *HTTPSBootstrap) Fetch(ctx context.Context, content protocolv4.NamespaceContent, output []byte) (int, error) {
	if err := ctx.Err(); err != nil {
		return 0, err
	}
	if len(p.state) != int(content.EncodedBytes) || len(p.state) > len(output) {
		return 0, errors.New("bootstrap state length mismatch")
	}
	// The original namespace owner verifies content.Digest before installation.
	return copy(output, p.state), nil
}
func (p *HTTPSBootstrap) Close() {
	if p != nil && p.client != nil {
		p.client.CloseIdleConnections()
	}
}

// Each HTTP socket is opened on the explicit host-selected thread. The native
// transport retains ordinary TLS and response limits and owns the returned socket.
func scopedControlDial(scope assemblyv4.NativeDialScope) func(context.Context, string, string) (net.Conn, error) {
	return func(ctx context.Context, network, address string) (net.Conn, error) {
		var connection net.Conn
		err := assemblyv4.RunNativeDial(ctx, scope, func() error {
			var err error
			connection, err = (&net.Dialer{}).DialContext(ctx, network, address)
			return err
		})
		if err != nil && connection != nil {
			err = errors.Join(err, connection.Close())
			connection = nil
		}
		return connection, err
	}
}
