[package]
name = "flowersec-fuzz"
version = "0.0.0"
publish = false
edition = "2024"
license = "MIT"

[package.metadata]
cargo-fuzz = true

[dependencies]
flowersec = { version = "=3.0.0", path = "..", features = ["__flowersec_internal_fuzzing"] }
libfuzzer-sys = "0.4"

[[bin]]
name = "artifact"
path = "fuzz_targets/artifact.rs"
test = false
doc = false
bench = false

[[bin]]
name = "admission"
path = "fuzz_targets/admission.rs"
test = false
doc = false
bench = false

[[bin]]
name = "protocol"
path = "fuzz_targets/protocol.rs"
test = false
doc = false
bench = false
