// Code generated by idlgen. DO NOT EDIT.

import type { Client } from "../../../client.js";
import { connectDirect } from "../../../direct-client/connect.js";
import type { DirectConnectOptions } from "../../../direct-client/connect.js";
import { connectTunnel } from "../../../tunnel-client/connect.js";
import type { TunnelConnectOptions } from "../../../tunnel-client/connect.js";
import type { ChannelInitGrant } from "../../../gen/flowersec/controlplane/v1.gen.js";
import type { DirectConnectInfo } from "../../../gen/flowersec/direct/v1.gen.js";
import {
  createDemoClient,
} from "./v1.rpc.gen.js";

export type DemoSession = Client & Readonly<{ demo: ReturnType<typeof createDemoClient> }>;

export function createDemoSession(client: Client): DemoSession {
  return { ...client, demo: createDemoClient(client.rpc) };
}

export async function connectDemoTunnel(grant: ChannelInitGrant, opts: TunnelConnectOptions): Promise<DemoSession>;
export async function connectDemoTunnel(grant: unknown, opts: TunnelConnectOptions): Promise<DemoSession> {
  const client = await connectTunnel(grant, opts);
  return createDemoSession(client);
}

export async function connectDemoDirect(info: DirectConnectInfo, opts: DirectConnectOptions): Promise<DemoSession>;
export async function connectDemoDirect(info: unknown, opts: DirectConnectOptions): Promise<DemoSession> {
  const client = await connectDirect(info, opts);
  return createDemoSession(client);
}
