// Generate version-pinned reference data. No host Unicode algorithms are used.
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";

const directory = import.meta.dirname;
const manifest = JSON.parse(fs.readFileSync(path.join(directory,"normalization_sources.json"),"utf8"));
const args = process.argv.slice(2);
assert.ok(args.length === 0 || (args.length === 1 && args[0] === "--check") || (args.length === 2 && args[0] === "--import-sources" && path.isAbsolute(args[1])), "usage: generate_normalization.mjs [--check | --import-sources ABSOLUTE_DIRECTORY]");
const check = args[0] === "--check", importing = args[0] === "--import-sources";
const sourceBytes = new Map();
for (const [name, entry] of Object.entries(manifest.sources)) {
  assert.ok(["UnicodeData.txt","DerivedNormalizationProps.txt","NormalizationTest.txt","DerivedAge.txt"].includes(name));
  const local = path.join(directory,name), input = importing && name !== "DerivedAge.txt" ? path.join(args[1],name) : local;
  const bytes = fs.readFileSync(input);
  assert.equal(createHash("sha256").update(bytes).digest("hex"),entry.sha256,`${name}: source SHA drift`);
  sourceBytes.set(name,bytes);
}
// Verify every input before importing any source. --check is strictly read-only.
if (importing) for (const [name,bytes] of sourceBytes) {
  const target = path.join(directory,name);
  if (fs.existsSync(target)) assert.deepEqual(fs.readFileSync(target),bytes,`${name}: refusing to overwrite another source`);
  else fs.writeFileSync(target,bytes,{flag:"wx"});
}
const scalar = (hex) => Number.parseInt(hex,16);
const ccc = [], decompositions = [], excluded = new Set();
for (const line of sourceBytes.get("DerivedNormalizationProps.txt").toString().split(/\r?\n/u)) {
  const match = /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*Full_Composition_Exclusion\s*(?:#|$)/u.exec(line);
  if (!match) continue;
  for (let cp=scalar(match[1]);cp<=scalar(match[2] ?? match[1]);cp++) excluded.add(cp);
}
const records = new Map();
for (const line of sourceBytes.get("UnicodeData.txt").toString().split(/\r?\n/u)) {
  if (!line) continue;
  const fields = line.split(";"); assert.equal(fields.length,15);
  const cp = scalar(fields[0]), combining = Number(fields[3]);
  assert.ok(!records.has(cp)); records.set(cp,fields);
  if (combining) ccc.push([cp,combining]);
  if (fields[5] && !fields[5].startsWith("<")) decompositions.push([cp,fields[5].split(" ").map(scalar)]);
}
const compositions = [], compositionKeys = new Set();
for (const [cp,parts] of decompositions) {
  if (excluded.has(cp)) continue;
  assert.equal(parts.length,2, "non-pair decomposition must be excluded");
  assert.equal(Number(records.get(parts[0])[3]),0, "non-starter must be excluded");
  const key = `${parts[0]},${parts[1]}`;
  assert.ok(!compositionKeys.has(key),"duplicate canonical composition"); compositionKeys.add(key);
  compositions.push([...parts,cp]);
}
const assigned = [];
for (const line of sourceBytes.get("DerivedAge.txt").toString().split(/\r?\n/u)) {
  const match = /^([0-9A-F]+)(?:\.\.([0-9A-F]+))?\s*;\s*(\d+)\.(\d+)/u.exec(line);
  if (!match) continue;
  assert.ok(Number(match[3]) < 15 || (Number(match[3]) === 15 && Number(match[4]) <= 1));
  assigned.push([scalar(match[1]),scalar(match[2] ?? match[1])]);
}
assigned.sort((a,b)=>a[0]-b[0]);
const merged = [];
for (const [lo,hi] of assigned) {
  const previous=merged.at(-1);
  if (previous && lo<=previous[1]+1) previous[1]=Math.max(previous[1],hi); else merged.push([lo,hi]);
}
const data = {unicode_version:manifest.unicode_version,sources:manifest.sources,ccc,decompositions,compositions,assigned:merged};
const expected = JSON.stringify(data)+"\n", target=path.join(directory,"normalization_generated.json");
if (check) assert.equal(fs.readFileSync(target,"utf8"),expected,"normalization table drift");
else fs.writeFileSync(target,expected);
// Compile the same pinned tables into the receiver. No testdata files or host
// Unicode implementation are needed when a deployed SDK validates wire text.
const decompositionMap = new Map(decompositions);
function expand(cp) { return decompositionMap.has(cp) ? decompositionMap.get(cp).flatMap(expand) : [cp]; }
const expanded = decompositions.map(([cp]) => [cp,expand(cp)]);
const width = Math.max(...expanded.map(([,parts]) => parts.length),3);
const goRaw = `// Code generated by testdata/unicode15_1/generate_normalization.mjs; DO NOT EDIT.
package unicode151
const MaxCanonicalDecomposition = ${width}
var combiningClasses = [...]struct { cp rune; class uint8 }{${ccc.map(([cp,cl])=>`{${cp},${cl}},`).join("")}}
var canonicalDecompositions = [...]struct { cp rune; count uint8; parts [${width}]rune }{${expanded.map(([cp,parts])=>`{${cp},${parts.length},[${width}]rune{${parts.join(",")}}},`).join("")}}
var canonicalCompositions = [...]struct { a,b,result rune }{${[...compositions].sort((a,b)=>a[0]-b[0]||a[1]-b[1]).map(parts=>`{${parts.join(",")}},`).join("")}}
`;
const formatted = spawnSync("gofmt",{input:goRaw,encoding:"utf8"});
assert.equal(formatted.status,0,formatted.stderr);
const goTarget = path.resolve(directory,"../../flowersec-go/internal/unicode151/normalization_generated.go");
if (check) assert.equal(fs.readFileSync(goTarget,"utf8"),formatted.stdout,"Go normalization table drift");
else fs.writeFileSync(goTarget,formatted.stdout);
// Fixed-width immutable lookup strings avoid a per-Environment dynamic map
// and carry the same fully expanded decomposition used by the Go receiver.
const hex = (n, digits) => n.toString(16).padStart(digits, "0");
const hexRows = (rows, widths) => rows.map(row => row.map((n, i) => hex(n, widths[i])).join("")).join("");
const literal = value => value.match(/.{1,120}/gu).map(s => `  "${s}"`).join(" +\n");
const tsRaw = `// Code generated by testdata/unicode15_1/generate_normalization.mjs; DO NOT EDIT.
export const maxCanonicalDecomposition = ${width};
const classes =\n${literal(hexRows(ccc, [6, 2]))};
const decompositions =\n${literal(hexRows(expanded.map(([cp, parts]) => [cp, parts.length, ...parts, ...Array(width - parts.length).fill(0)]), [6, 2, ...Array(width).fill(6)]))};
const compositions =\n${literal(hexRows([...compositions].sort((a, b) => a[0] - b[0] || a[1] - b[1]), [6, 6, 6]))};
const assigned =\n${literal(hexRows(merged, [6, 6]))};
function number(s: string, at: number, digits: number): number { return Number.parseInt(s.slice(at, at + digits), 16); }
function find(s: string, width: number, cp: number): number {
  let lo = 0, hi = s.length / width;
  while (lo < hi) { const mid = lo + Math.floor((hi - lo) / 2); if (number(s, mid * width, 6) < cp) lo = mid + 1; else hi = mid; }
  return lo < s.length / width && number(s, lo * width, 6) === cp ? lo * width : -1;
}
export function combiningClass(cp: number): number { const at = find(classes, 8, cp); return at < 0 ? 0 : number(classes, at + 6, 2); }
export function assignedScalar(cp: number): boolean {
  let lo = 0, hi = assigned.length / 12;
  while (lo < hi) { const mid = lo + Math.floor((hi - lo) / 2); if (number(assigned, mid * 12 + 6, 6) < cp) lo = mid + 1; else hi = mid; }
  return lo < assigned.length / 12 && number(assigned, lo * 12, 6) <= cp;
}
export function canonicalParts(cp: number, output: Uint32Array, offset: number): number {
  const at = find(decompositions, ${8 + 6 * width}, cp);
  if (at < 0) { output[offset] = cp; return 1; }
  const n = number(decompositions, at + 6, 2);
  for (let i = 0; i < n; i++) output[offset + i] = number(decompositions, at + 8 + 6 * i, 6);
  return n;
}
export function composePair(a: number, b: number): number {
  if (a >= 0x1100 && a < 0x1100 + 19 && b >= 0x1161 && b < 0x1161 + 21) return 0xac00 + ((a - 0x1100) * 21 + b - 0x1161) * 28;
  if (a >= 0xac00 && a < 0xac00 + 11172 && (a - 0xac00) % 28 === 0 && b > 0x11a7 && b < 0x11a7 + 28) return a + b - 0x11a7;
  let lo = 0, hi = compositions.length / 18;
  while (lo < hi) {
    const mid = lo + Math.floor((hi - lo) / 2), x = number(compositions, mid * 18, 6), y = number(compositions, mid * 18 + 6, 6);
    if (x < a || x === a && y < b) lo = mid + 1; else hi = mid;
  }
  return lo < compositions.length / 18 && number(compositions, lo * 18, 6) === a && number(compositions, lo * 18 + 6, 6) === b ? number(compositions, lo * 18 + 12, 6) : -1;
}
`;
const tsTarget = path.resolve(directory, "../../flowersec-ts/src/generated/normalization151.ts");
if (check) assert.equal(fs.readFileSync(tsTarget, "utf8"), tsRaw, "TypeScript normalization table drift");
else fs.writeFileSync(tsTarget, tsRaw);
console.log(`Unicode ${data.unicode_version} NFC tables ${check ? "verified" : "generated"}: ${ccc.length} combining classes, ${decompositions.length} decompositions, ${compositions.length} compositions.`);
