import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const directory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(directory, "../..");
const sourcePath = path.join(directory, "DerivedAge.txt");
const licensePath = path.join(directory, "LICENSE.txt");
const sourceSHA256 = "04e16379344bdb9973cdb6f6bf0a5dd66f7cd41b014cd9f79d848768ae757256";
const licenseSHA256 = "e7a93b009565cfce55919a381437ac4db883e9da2126fa28b91d12732bc53d96";
const check = process.argv.slice(2).includes("--check");

const source = await readFile(sourcePath, "utf8");
const license = await readFile(licensePath, "utf8");
assertDigest(source, sourceSHA256, "DerivedAge.txt");
assertDigest(license, licenseSHA256, "LICENSE.txt");

const ranges = [];
for (const line of source.split(/\r?\n/u)) {
  const match = /^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*([0-9]+)\.([0-9]+)/u.exec(line);
  if (match === null) continue;
  const major = Number(match[3]);
  const minor = Number(match[4]);
  if (major > 15 || (major === 15 && minor > 1)) continue;
  ranges.push([Number.parseInt(match[1], 16), Number.parseInt(match[2] ?? match[1], 16)]);
}
ranges.sort((left, right) => left[0] - right[0]);
const merged = [];
for (const range of ranges) {
  const previous = merged.at(-1);
  if (previous !== undefined && range[0] <= previous[1] + 1) previous[1] = Math.max(previous[1], range[1]);
  else merged.push([...range]);
}
const rangesHex = merged.map(([start, end]) => hex(start) + hex(end)).join("");

const outputs = new Map([
  ["flowersec-go/internal/unicode151/table_generated.go", goSource(rangesHex)],
  ["flowersec-ts/src/generated/unicode151.ts", typeScriptSource(rangesHex)],
  ["flowersec-rust/src/unicode151_generated.rs", rustSource(rangesHex)],
  ["flowersec-swift/Sources/Flowersec/Unicode151Generated.swift", swiftSource(rangesHex)],
]);

for (const [relative, rawExpected] of outputs) {
  const expected = relative.endsWith(".go") ? formatGo(rawExpected) : rawExpected;
  const outputPath = path.join(repositoryRoot, relative);
  if (check) {
    const actual = await readFile(outputPath, "utf8").catch(() => "");
    if (actual !== expected) throw new Error(`${relative} is not generated from Unicode 15.1 DerivedAge.txt`);
  } else {
    await writeFile(outputPath, expected);
  }
}

console.log(`Unicode 15.1 assigned tables ${check ? "verified" : "generated"}: ${merged.length} ranges`);

function assertDigest(value, expected, name) {
  const actual = createHash("sha256").update(value).digest("hex");
  if (actual !== expected) throw new Error(`${name} SHA-256 mismatch: ${actual}`);
}

function formatGo(value) {
  const result = spawnSync("gofmt", { input: value, encoding: "utf8" });
  if (result.status !== 0) throw new Error(`gofmt failed: ${result.stderr}`);
  return result.stdout;
}

function hex(value) {
  return value.toString(16).toUpperCase().padStart(6, "0");
}

function splitLiteral(value, width, prefix, suffix) {
  const chunks = [];
  for (let offset = 0; offset < value.length; offset += width) chunks.push(value.slice(offset, offset + width));
  const continuation = suffix.endsWith(",") ? "" : " +";
  return chunks.map((chunk, index) => `${prefix}${chunk}${suffix}${index + 1 === chunks.length ? "" : continuation}`).join("\n");
}

function goSource(value) {
  return `// Code generated by testdata/unicode15_1/generate_tables.mjs; DO NOT EDIT.\npackage unicode151\n\nconst Version = "15.1.0"\n\nconst assignedRangesHex =\n${splitLiteral(value, 120, "\t\"", "\"")}\n\nfunc Assigned(value rune) bool {\n\tencoded := uint32(value)\n\tfor offset := 0; offset < len(assignedRangesHex); offset += 12 {\n\t\tstart := parseHex(assignedRangesHex[offset : offset+6])\n\t\tend := parseHex(assignedRangesHex[offset+6 : offset+12])\n\t\tif encoded >= start && encoded <= end { return true }\n\t}\n\treturn false\n}\n\nfunc parseHex(value string) uint32 {\n\tvar result uint32\n\tfor _, current := range []byte(value) {\n\t\tresult <<= 4\n\t\tif current >= '0' && current <= '9' { result |= uint32(current - '0') } else { result |= uint32(current-'A') + 10 }\n\t}\n\treturn result\n}\n`;
}

function typeScriptSource(value) {
  return `// Code generated by testdata/unicode15_1/generate_tables.mjs; DO NOT EDIT.\nexport const UNICODE_15_1_VERSION = "15.1.0";\n\nconst ASSIGNED_RANGES_HEX =\n${splitLiteral(value, 120, "  \"", "\"")};\n\nexport function unicode151Assigned(codePoint: number): boolean {\n  for (let offset = 0; offset < ASSIGNED_RANGES_HEX.length; offset += 12) {\n    const start = Number.parseInt(ASSIGNED_RANGES_HEX.slice(offset, offset + 6), 16);\n    const end = Number.parseInt(ASSIGNED_RANGES_HEX.slice(offset + 6, offset + 12), 16);\n    if (codePoint >= start && codePoint <= end) return true;\n  }\n  return false;\n}\n`;
}

function rustSource(value) {
  return `// Code generated by testdata/unicode15_1/generate_tables.mjs; DO NOT EDIT.\npub(crate) const UNICODE_VERSION: &str = "15.1.0";\n\nconst ASSIGNED_RANGES_HEX: &str = concat!(\n${splitLiteral(value, 120, "    \"", "\",")}\n);\n\npub(crate) fn assigned(code_point: u32) -> bool {\n    let _ = UNICODE_VERSION;\n    ASSIGNED_RANGES_HEX\n        .as_bytes()\n        .as_chunks::<12>()\n        .0\n        .iter()\n        .any(|range| {\n            let start = parse_hex(&range[..6]);\n            let end = parse_hex(&range[6..]);\n            code_point >= start && code_point <= end\n        })\n}\n\nfn parse_hex(value: &[u8]) -> u32 {\n    value.iter().fold(0, |result, current| {\n        (result << 4)\n            | if current.is_ascii_digit() {\n                u32::from(current - b'0')\n            } else {\n                u32::from(current - b'A') + 10\n            }\n    })\n}\n`;
}

function swiftSource(value) {
  return `// Code generated by testdata/unicode15_1/generate_tables.mjs; DO NOT EDIT.\nenum Unicode151Generated {\n  static let version = "15.1.0"\n  private static let assignedRangesHex =\n${splitLiteral(value, 120, "    \"", "\"")}\n\n  static func assigned(_ scalar: Unicode.Scalar) -> Bool {\n    let encoded = scalar.value\n    var offset = assignedRangesHex.startIndex\n    while offset < assignedRangesHex.endIndex {\n      let middle = assignedRangesHex.index(offset, offsetBy: 6)\n      let end = assignedRangesHex.index(middle, offsetBy: 6)\n      let lower = UInt32(assignedRangesHex[offset..<middle], radix: 16)!\n      let upper = UInt32(assignedRangesHex[middle..<end], radix: 16)!\n      if encoded >= lower && encoded <= upper { return true }\n      offset = end\n    }\n    return false\n  }\n}\n`;
}
